baseURL = "https://shard-for-obsidian.github.io/shard/"
languageCode = "en-us"
title = "Shard Plugin Marketplace"

[params]
  description = "Discover and install Obsidian plugins via OCI registries"
  author = "Shard Project"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  plugins = "/plugins/:filename/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Plugins"
  url = "/plugins/"
  weight = 2
